# Generated by Django 2.2.4 on 2019-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-fecha'], 'verbose_name': 'Data', 'verbose_name_plural': 'Datos'},
        ),
        migrations.AddField(
            model_name='data',
            name='sede',
            field=models.CharField(choices=[('Casa Central', 'Casa Central'), ('Antonio Varas', 'Antonio Varas'), ('Alameda', 'Alameda'), ('Campus Arauco', 'Campus Arauco'), ('Maipú', 'Maipú'), ('Melipilla', 'Melipilla'), ('Padre Alonso Ovalle', 'Padre Alonso Ovalle'), ('Plaza Norte', 'Plaza Norte'), ('Plaza Oeste', 'Plaza Oeste'), ('Plaza Vespucio', 'Plaza Vespucio'), ('Puente Alto', 'Puente Alto'), ('San Andrés de Concepción', 'San Andrés de Concepción'), ('San Bernardo', 'San Bernardo'), ('San Carlos de Apoquindo', 'San Carlos de Apoquindo'), ('San Joaquín', 'San Joaquín'), ('Valparaíso', 'Valparaíso'), ('Viña del Mar', 'Viña del Mar'), ('No especificado', 'No especificado')], default='No especificado', max_length=255, verbose_name='Sede'),
        ),
    ]
