# Generated by Django 2.2.4 on 2019-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20190901_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hora_fin',
            field=models.CharField(max_length=5, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='data',
            name='hora_inicio',
            field=models.CharField(max_length=5, verbose_name='Hora Inicio'),
        ),
    ]
