# Generated by Django 2.2.4 on 2019-12-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_auto_20190901_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runAlumno', models.CharField(max_length=12, verbose_name='RUN_alumno')),
                ('rating_value', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='rating')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created'],
            },
        ),
    ]
