# Generated by Django 2.2.4 on 2019-12-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_starrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starrating',
            old_name='runAlumno',
            new_name='run',
        ),
    ]
